pool:
    vmImage: ubuntu-latest

steps:
    - task: NodeTool@0
      displayName: Use Node.js 20
      inputs:
          versionSpec: "20.x"
          checkLatest: true

    - script: npm ci
      displayName: Install dependencies

    - script: npm run build
      displayName: Build TypeScript

    - script: npm start
      displayName: Run QA report generator
      env:
          AZDO_ORG_URL: $(AZDO_ORG_URL)
          AZDO_PROJECT: $(AZDO_PROJECT)
          AZDO_TEAM: $(AZDO_TEAM)
          AZDO_PAT: $(AZDO_PAT)
          CONFLUENCE_BASE_URL: $(CONFLUENCE_BASE_URL)
          CONFLUENCE_PAGE_ID: $(CONFLUENCE_PAGE_ID)
          CONFLUENCE_EMAIL: $(CONFLUENCE_EMAIL)
          CONFLUENCE_API_TOKEN: $(CONFLUENCE_API_TOKEN)
          CONFLUENCE_PARENT_PAGE_ID: $(CONFLUENCE_PARENT_PAGE_ID)

    - task: PublishBuildArtifacts@1
      displayName: Upload QA report artifact
      inputs:
          PathtoPublish: reports
          ArtifactName: qa-report
          publishLocation: Container
