trigger:
    branches:
        include:
            - main

pool:
    vmImage: ubuntu-latest

steps:
    - task: NodeTool@0
      displayName: Use Node.js 20
      inputs:
          versionSpec: "20.x"
          checkLatest: true

    - script: npm ci
      displayName: Install dependencies

    - script: npm run build
      displayName: Build TypeScript

    - script: npm start
      displayName: Run QA report generator
      env:
          AZDO_ORG_URL: $(AZDO_ORG_URL)
          AZDO_PROJECT: $(AZDO_PROJECT)
          AZDO_TEAM: $(AZDO_TEAM)
          AZDO_PAT: $(AZDO_PAT)
